main.py
from flask import Flask
from routes.home import home_route # import the home route from the routes folder
from routes.users import user_route # import the users routes from routes folder

#INITIALIZATION
app = Flask(__name__)

app.register_blueprint(home_route) # register the imported home route varaible
app.register_blueprint(user_route, url_prefix="/users") # register the imported user route variable

#EXECUTION
app.run(debug=True)

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route("/")
def home():
    return render_template("index.html")

routes/users.py
from flask import Blueprint, render_template, request
from database.user import USERS 

user_route = Blueprint("user", __name__)

@user_route.route("/")
def user_list(): # list the users
    return render_template("user_list.html", users=USERS)

@user_route.route("/", methods=["POST"])
def add_user(): # insert the user data
    data = request.json

    new_user = {
        "id": len(USERS) + 1,
        "name": data['name'],
        "email": data['email'],
    }

    USERS.append(new_user)

    return render_template("user_item.html", user=new_user)

@user_route.route("/new")
def form_user(): # form to register a user
    return render_template("form_user.html")

@user_route.route("/<int:user_id>")
def detail_user(user_id): # show user details

    user = list(filter(lambda c: c['id'] == user_id, USERS))[0]
    return render_template("detail_user.html", user=user)

@user_route.route("/<int:user_id>/edit")
def form_edit_user(user_id): # form to edit a user
    user = None
    for c in USERS:
        if c['id'] == user_id:
            user = c

    return render_template("form_user.html", user=user)

@user_route.route("/<int:user_id>/update", methods=["PUT"])
def update_user(user_id): # update user data
    updated_user = None
    #get data from update form
    data = request.json

    #get user from id
    for c in USERS:
        if c['id'] == user_id:
            c['name'] = data['name']
            c['email'] = data['email']

            updated_user = c

    #edit user
    return render_template('user_item.html', user=updated_user)

@user_route.route("/<int:user_id>/delete", methods=["DELETE"])
def delete_user(user_id): # delete user data
    global USERS
    USERS = [ u for u in USERS if u["id"] != user_id ]
    return {"deleted" : "ok"}

templates/detail_user.html
<ul>
    <li>ID: {{user.id}}</li>
    <li>NAME: {{user.name}}</li>
    <li>E-MAIL: {{user.email}}</li>
</ul>

templates/form_user.html
<form class="c-form"
        {% if user %}
            action="{{ url_for('user.update_user', user_id=user.id) }}"
        {% else %}
            action="{{ url_for('user.add_user') }}"
        {% endif %}
        
        method="{% if user %}PUT{% else %}POST{% endif %}"

        {% if user %}   
            c-swap="#user-{{user.id}}"
        {% else %}
          c-append="#user_list"
        {% endif %}
        >

    <div class="mb-3">
      <label class="form-label">Name</label>
      <input type="text" class="form-control" name="name" {% if user %}value="{{user.name}}"{% endif %}>
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" name="email" {% if user %}value="{{user.email}}"{% endif %}>
    </div>

    <button type="submit" class="btn btn-primary">
      {% if user %}Save{% else %}Create{% endif %}
    </button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body>

    <div class="container">
      <h1 class="text-center">User Management</h1>

      <!-- Add user form -->
      <div id="user-form"
        c-container="{{ url_for('user.form_user') }}"></div>

      <hr>

      <!-- User List -->
      <h2>User List</h2>
      <div c-container="{{ url_for('user.user_list') }}"></div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="show-user"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>

  </body>
</html>

templates/user_item.html
<tr id="user-{{user.id}}">
    <th scope="row">{{ user.id }}</th>
    <td>{{ user.name }}</td>
    <td>{{ user.email }}</td>
    <td>
        <button class="btn btn-secondary" 
            c-get="{{ url_for('user.detail_user', user_id=user.id) }}"
            c-target="#show-user"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
                Show
        </button>

        <button class="btn btn-primary"
            c-get="{{ url_for('user.form_edit_user', user_id=user.id) }}"
            c-target="#user-form">
                Edit
        </button>

        <button class="btn btn-danger" 
            c-delete="{{ url_for('user.delete_user', user_id=user.id) }}"
            c-remove-closest="tr">
                Delete
        </button>
    </td>
</tr>

templates/user_list.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody id="user_list">

        {% for user in users %}
            {% include 'user_item.html' %}
        {% endfor %}

    </tbody>
  </table>